# Generated by Django 2.1 on 2018-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(default='', help_text='No spaces. this is the URL', max_length=16),
            preserve_default=False,
        ),
    ]
