# Generated by Django 2.1 on 2018-09-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0003_auto_20180912_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('youtube_video_link', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('length', models.IntegerField(help_text='in minutes')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='northern_winter_beat.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(help_text="Accepts HTML etc. make sure you don't abuse this!"),
        ),
    ]
