# Generated by Django 2.1 on 2018-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0004_auto_20180912_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
