# Generated by Django 2.1 on 2018-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0006_auto_20180912_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='youtube_video_link',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
