# Generated by Django 2.1 on 2018-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0007_auto_20180912_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
