# Generated by Django 2.1 on 2018-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='Can contain HTML, however be careful as this could make fucked up shit'),
        ),
    ]
