# Generated by Django 2.1 on 2018-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0010_auto_20180915_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='artist',
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
