# Generated by Django 2.1 on 2018-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0011_auto_20180915_0747'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(help_text="Accepts HTML etc. make sure you don't abuse this!", verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=64, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
    ]
