# Generated by Django 2.1 on 2018-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0013_winterbeatsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='body',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='title_en'
        ),
        migrations.AddField(
            model_name='page',
            name='title_da',
            field=models.CharField(default='placeholder',
                                   max_length=64,
                                   verbose_name='title [danish]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='body_da',
            field=models.TextField(default="",
                                   help_text="Accepts HTML etc. make sure you don't abuse this!",
                                   verbose_name='body [danish]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=64, verbose_name='title [english]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_en',
            field=models.TextField(help_text="Accepts HTML etc. make sure you don't abuse this!", verbose_name='body [english]'),
        ),
    ]
