# Generated by Django 2.1 on 2018-10-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0014_auto_20181009_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='description',
            new_name='description_en'
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body_en'
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='artist',
            name='description_da',
            field=models.TextField(blank=True, default='', verbose_name='description [danish]'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_da',
            field=models.CharField(default='placeholder', max_length=128, verbose_name='title [danish]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default=' ', max_length=128, verbose_name='title [english]'),
            preserve_default=False,
        ),
    ]
