# Generated by Django 2.1 on 2018-10-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0015_auto_20181009_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artist', 'verbose_name_plural': 'artists'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='winterbeatsettings',
            options={'verbose_name': 'Winterbeat Settings'},
        ),
    ]
