# Generated by Django 2.1 on 2018-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0016_auto_20181010_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_da',
            field=models.TextField(default='', help_text='Can contain HTML, however be careful as this could make fucked up shit', verbose_name='body [Danish]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='description_da',
            field=models.TextField(blank=True, default='', verbose_name='description [Danish]'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='description [English]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_da',
            field=models.TextField(help_text="Accepts HTML etc. make sure you don't abuse this!", verbose_name='body [Danish]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_en',
            field=models.TextField(help_text="Accepts HTML etc. make sure you don't abuse this!", verbose_name='body [English]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_da',
            field=models.CharField(max_length=64, verbose_name='title [Danish]'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=64, verbose_name='title [English]'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=models.TextField(help_text='Can contain HTML, however be careful as this could make fucked up shit', verbose_name='body [English]'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_da',
            field=models.CharField(max_length=128, verbose_name='title [Danish]'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name='title [English]'),
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='bottom_text_da',
            field=models.TextField(default='', help_text='The paragraph below the list of bands. It is hidden if empty', verbose_name='Bottom text [Danish]'),
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='bottom_text_en',
            field=models.TextField(default='', help_text='The paragraph below the list of bands. It is hidden if empty', verbose_name='Bottom text [English]'),
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='top_text_da',
            field=models.TextField(default='', help_text='the paragraph above the list of bands. Is hidden if empty', verbose_name='Top text [Danish]'),
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='top_text_en',
            field=models.TextField(default='', help_text='the paragraph above the list of bands. Is hidden if empty', verbose_name='Top text [English]'),
        ),
    ]
