# Generated by Django 2.1.1 on 2018-10-21 07:58

from django.db import migrations, models


def add_sort_order(apps, schema_editor):
    Artist = apps.get_model("northern_winter_beat", "Artist")
    for artist in Artist.objects.all():
        artist.sort_order = artist.pk
        artist.save()


class Migration(migrations.Migration):
    dependencies = [
        ('northern_winter_beat', '0017_auto_20181010_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('sort_order',), 'verbose_name': 'artist', 'verbose_name_plural': 'artists'},
        ),
        migrations.AddField(
            model_name='artist',
            name='one_line',
            field=models.BooleanField(default=False,
                                      help_text='Do you want title on splash screen on one singular line?',
                                      verbose_name='One line'),
        ),
        migrations.AddField(
            model_name='artist',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='show_nav_bar',
            field=models.BooleanField(default=False, help_text='Show the bar of pages on top or not.',
                                      verbose_name='Show navigation bar'),
        ),
        migrations.RunPython(add_sort_order, lambda: None)
    ]
