# Generated by Django 2.1.1 on 2018-10-21 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0018_auto_20181021_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time when this band is going to be released on the website.', verbose_name='Release date'),
        ),
    ]
