# Generated by Django 2.1.1 on 2018-11-21 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0021_auto_20181031_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='winterbeatsettings',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 26, 0, 0), help_text='The date the festival starts', verbose_name='Start dato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winterbeatsettings',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 24, 0, 0), help_text='The date the festival starts', verbose_name='Start dato'),
            preserve_default=False,
        ),
    ]
