# Generated by Django 2.1.1 on 2018-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0023_auto_20181121_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date',
            field=models.DateField(blank=True, help_text='The day the artist is going to play', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='end_date',
            field=models.DateField(help_text='The date the festival ends', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='start_date',
            field=models.DateField(help_text='The date the festival starts', verbose_name='Start date'),
        ),
    ]
