# Generated by Django 2.1.1 on 2018-12-01 11:30

from django.db import migrations, models
import django.db.models.deletion


def fill_concerts(apps, schema_editor):
    Artist = apps.get_model("northern_winter_beat", "Artist")
    Concert = apps.get_model("northern_winter_beat", "Concert")
    for artist in Artist.objects.exclude(concert_date=None):
        Concert.objects.create(
            artist=artist,
            date=artist.concert_date,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('northern_winter_beat', '0026_auto_20181201_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, help_text='The day the artist is going to play', null=True,
                                          verbose_name='date')),
                ('artist', models.ForeignKey(help_text='The artist that is going to play the concert',
                                             on_delete=django.db.models.deletion.CASCADE,
                                             to='northern_winter_beat.Artist')),
            ],
        ),
        migrations.RunPython(fill_concerts)
    ]
