# Generated by Django 2.1.1 on 2018-12-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0027_concert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'concert', 'verbose_name_plural': 'concerts'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='concert_date',
        ),
    ]
