# Generated by Django 2.1.1 on 2018-12-01 15:31

from django.db import migrations, models


def add_sort_order(apps, schema_editor):
    Concert = apps.get_model("northern_winter_beat", "Concert")
    for concert in Concert.objects.all():
        concert.sort_order = concert.pk
        concert.save()


class Migration(migrations.Migration):
    dependencies = [
        ('northern_winter_beat', '0028_auto_20181201_1336'),
    ]

    operations = [
        # https://stackoverflow.com/questions/28429933/django-migrations-using-runpython-to-commit-changes
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ('sort_order',), 'verbose_name': 'concert', 'verbose_name_plural': 'concerts'},
        ),
        migrations.AddField(
            model_name='concert',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.RunPython(add_sort_order),

        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]

