# Generated by Django 2.1.1 on 2019-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0032_auto_20190113_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winterbeatsettings',
            name='show_schedule',
            field=models.BooleanField(default=False, help_text='Show the page with the date each artist is going to play', verbose_name='Show schedule'),
        ),
    ]
