# Generated by Django 2.1.7 on 2019-02-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('northern_winter_beat', '0033_auto_20190221_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinterbeatSettings',
            new_name='Festival',
        ),
    ]
