# Generated by Django 2.1.7 on 2019-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='bottom_text_da',
            field=models.TextField(blank=True, default='', help_text='The paragraph below the list of bands. It is hidden if empty', verbose_name='Bottom text [Danish]'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='bottom_text_en',
            field=models.TextField(blank=True, default='', help_text='The paragraph below the list of bands. It is hidden if empty', verbose_name='Bottom text [English]'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='top_text_da',
            field=models.TextField(blank=True, default='', help_text='the paragraph above the list of bands. Is hidden if empty', verbose_name='Top text [Danish]'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='top_text_en',
            field=models.TextField(blank=True, default='', help_text='the paragraph above the list of bands. Is hidden if empty', verbose_name='Top text [English]'),
        ),
    ]
