# Generated by Django 2.1.7 on 2019-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20190221_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='theme',
            field=models.CharField(default='wayupnorth', help_text="just dont touch if Casper hasn't told you to.", max_length=128),
            preserve_default=False,
        ),
    ]
