# Generated by Django 2.1.7 on 2019-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_festival_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='facebook_link',
            field=models.CharField(blank=True, help_text='If you have a link to a facebook page', max_length=255, null=True, verbose_name='Link to Facebook'),
        ),
        migrations.AddField(
            model_name='festival',
            name='instagram_link',
            field=models.CharField(blank=True, help_text='If you have a link to a instagram page', max_length=255, null=True, verbose_name='Link to Instagram'),
        ),
    ]
