# Generated by Django 2.1.7 on 2019-03-04 08:53
from datetime import datetime

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Festival = apps.get_model("festivals", "Festival")

    Festival.objects.create(
        name="Way Up North",
        domain_name="wayupnorth.dk",
        theme="way-up-north",
        top_text_da="15. - 16. marts",
        top_text_en="15. - 16. march",
        bottom_text_da="Konferencierne: Carsten Holm • Jonny Hefty • Mark Jensen-Skovgaard",
        bottom_text_en="Host: Carsten Holm • Jonny Hefty • Mark Jensen-Skovgaard",
        description="Way Up North er yderst stolte af at kunne præsentere hele 24 nordjyske acts,"
                    " som optræder over weekenden den 15.-16. marts.\n"
                    "Way Up North festival har eksisteret siden 2004, og har fra starten "
                    "været en platform for præsentation af det bedste fra "
                    "live scenen i Nordjylland lige nu.",
        start_date=datetime(year=2019, day=15, month=3),
        end_date=datetime(year=2019, day=16, month=3),
    )
    Festival.objects.create(
        name="Northern Winter Beat",
        domain_name="winterbeat.dk",
        theme="winter-beat",
        top_text_da="Vi ses i 2020!",
        top_text_en="See you in 2020!",
        bottom_text_da="",
        bottom_text_en="",
        description="2020 skal sparkes godt i gang. Derfor laver vi i januar "
                    "Northern Winter Beat: en musikfestival, der vil fylde Aalborg "
                    "med lys og varme i en kold og mørk tid.",
        start_date=datetime(year=2020, day=20, month=1),
        end_date=datetime(year=2020, day=24, month=1),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('festivals', '0004_auto_20190224_1002'),
    ]

    operations = [

        migrations.RunPython(forwards_func, lambda x,y: None),
    ]
