# Generated by Django 2.1.7 on 2019-03-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_auto_20190304_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(help_text='The name of the stage', max_length=128, verbose_name='name')),
                ('festival', models.ForeignKey(help_text='The festival that the stage is used on', on_delete=django.db.models.deletion.CASCADE, to='festivals.Festival', verbose_name='festival')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='concert',
            name='festival',
        ),
        migrations.AddField(
            model_name='concert',
            name='stage',
            field=models.ForeignKey(default=1, help_text='The stage that the concert will be on', on_delete=django.db.models.deletion.CASCADE, to='festivals.Stage', verbose_name='stage'),
            preserve_default=False,
        ),
    ]
