# Generated by Django 2.1.7 on 2019-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_auto_20190306_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='time',
            field=models.TimeField(blank=True, help_text='The time the artist is going to play', null=True, verbose_name='time'),
        ),
    ]
