# Generated by Django 2.1.7 on 2019-03-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_concert_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='stage',
        ),
        migrations.AddField(
            model_name='artist',
            name='concert_time',
            field=models.DateTimeField(blank=True, help_text='The time of the concert', null=True, verbose_name='concert time'),
        ),
        migrations.AddField(
            model_name='artist',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='The stage that the concert will be on', null=True, on_delete=django.db.models.deletion.CASCADE, to='festivals.Stage', verbose_name='stage'),
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
