# Generated by Django 2.1.7 on 2019-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0009_remove_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name_da',
            field=models.CharField(default='stargate', help_text='The name of the stage', max_length=128, verbose_name='name [Danish]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='name_en',
            field=models.CharField(default='stargate', help_text='The name of the stage', max_length=128, verbose_name='name [English]'),
            preserve_default=False,
        ),
    ]
